Repository puppetlabs/puppetlabs-pe_status_check, pull requests merged in 2022-03, with the labels that each got.

#92 (SUP-2903) Check for new items in discard Directory
  README.md
  data/common.yaml
  lib/facter/pe_status_check.rb
  spec/acceptance/pe_status_check_spec.rb
Labels: enhancement

#91 (SUP-3099) Only Alert on 503 messages sent in last run interval
  lib/facter/pe_status_check.rb
  spec/acceptance/pe_status_check_spec.rb
Labels: bug

#94 Check for non-nil match in S0039
  lib/facter/pe_status_check.rb
Labels: bug

#95 PDK Template Update and octokit gem pin
  .rubocop.yml
  .sync.yml
  Gemfile
  manifests/init.pp
  metadata.json
  spec/default_facts.yml
Labels: maintenance

#93 (SUP-3116) Fix replica Detection in 2021.5
  lib/shared/pe_status_check.rb
Labels: bug

#98 (SUP-3122) Fix PSQL node detection in 2021.5
  lib/shared/pe_status_check.rb
Labels: bug

#105 (SUP-2917) Add indicator S0038 to check number of environments that are present in $codedir/environments
  README.md
  lib/facter/pe_status_check.rb
  spec/acceptance/pe_status_check_spec.rb
Labels: enhancement
