Repository puppetlabs/puppetlabs-pe_status_check, pull requests merged in 2022-06, with the labels that each got.

#99 (SUP-3315) Use cached state to determine node role
  lib/facter/pe_status_check.rb
  lib/facter/pe_status_check_role.rb
  lib/shared/pe_status_check.rb
Labels: enhancement, backwards-incompatible

#132 (SUP-3381) Add error handling to role fact
  lib/facter/pe_status_check_role.rb
Labels: bug

#135 SUP-3398 legacy primary support
  lib/facter/pe_status_check.rb
  lib/facter/pe_status_check_role.rb
Labels: bug

#137 (SUP-3400)(SUP-3401)(SUP-3402) Update Readme to explain facts further
  README.md
Labels: enhancement

#138 (sup-3146) update pe_status_check readme for non os specific logs whe…
  README.md
Labels: maintenance

#139 (SUP-3426) Use shorter timeout for facter execute
  lib/facter/agent_status_check.rb
  lib/facter/pe_status_check.rb
  lib/shared/pe_status_check.rb
Labels: enhancement

#140 (SUP-3423) Update metadata to reflect supported agent OS
  metadata.json
Labels: maintenance
