Repository puppetlabs/puppetlabs-pe_status_check, pull requests merged in 2022-01, with the labels that each got.

#18 (SUP-2898) Available Memory on the platform is less than 10%
  lib/facter/self_service.rb
  spec/acceptance/self_service_spec.rb
Labels: enhancement

#23 (SUP-2923) Replace unencrypted git protocol in .fixtures.yaml
  .fixtures.yml
Labels: maintenance

#28 (SUP-2915) Check if max-queued-requests is configured to above 150
  README.md
  lib/facter/self_service.rb
  spec/acceptance/self_service_spec.rb
Labels: enhancement

#34 Fixing intermittent issue with test for S0036
  spec/acceptance/self_service_spec.rb
Labels: maintenance

#27 (SUP-2909) Check that use_cached_catalog setting is false
  README.md
  lib/facter/self_service.rb
  spec/acceptance/self_service_spec.rb
Labels: enhancement

#39 (SUP-2939) Remove High Load Average test
  README.md
  lib/facter/self_service.rb
  spec/acceptance/self_service_spec.rb
Labels: maintenance, backwards-incompatible

#35 (SUP-2912) Added S0033 to check if Global Hiera is Hiera 5, added tests, updated README
  README.md
  lib/facter/self_service.rb
  spec/acceptance/self_service_spec.rb
Labels: enhancement

#29 (SUP-2919) - is puppet_metrics_collector::system configured
  README.md
  lib/facter/self_service.rb
  lib/shared/puppet_self_service.rb
  spec/acceptance/self_service_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: enhancement

#51 (SUP-2901) License check, tests and readme update
  README.md
  lib/facter/self_service.rb
  spec/acceptance/self_service_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: enhancement

#47 (SUP-2910) Check if older packages are still available to pe_repo
  README.md
  lib/facter/self_service.rb
  spec/acceptance/self_service_spec.rb
Labels: enhancement

#55 Updated Acceptance Test Dependencies
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#58 (SUP-2892) - No recent OOM errors logged in any JVM
  README.md
  lib/facter/self_service.rb
  spec/acceptance/self_service_spec.rb
Labels: enhancement

#59 (GH-52) Restrict S0006 to primaries
  lib/facter/self_service.rb
Labels: maintenance

#60 (maint) Remove contest information from the PR template
  .github/pull_request_template.md
Labels: maintenance

#32 Adding Agent only Fact check for expiring host cert
  lib/facter/agent_self_service.rb
  spec/acceptance/agent_self_service_spec.rb
Labels: enhancement

#38 (SUP-2913) Puppet not updated for more than a year
  README.md
  lib/facter/self_service.rb
  spec/acceptance/self_service_spec.rb
Labels: enhancement
