Repository puppetlabs/puppetlabs-pe_status_check, pull requests merged in 2022-02, with the labels that each got.

#64 (Issue #63) - Fixed the fact check in acceptance testing
  spec/acceptance/self_service_spec.rb
Labels: maintenance

#50 (SUP-2896) Check Avg Free JRubies
  lib/facter/self_service.rb
  lib/shared/puppet_self_service.rb
  spec/acceptance/self_service_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: enhancement

#44 (SUP-2918) Check If Puppet Server is sending 503s to agents
  README.md
  lib/facter/self_service.rb
  spec/acceptance/self_service_spec.rb
Labels: enhancement

#72 Pin octokit version to fix auto release workflowe
  Gemfile
Labels: maintenance

#69 Improve documentation
  README.md
Labels: enhancement

#74 Rename Module to pe_status_check
  lib/facter/agent_status_check.rb
  lib/facter/pe_status_check.rb
  lib/shared/pe_status_check.rb
  manifests/init.pp
  metadata.json
  spec/acceptance/agent_self_service_spec.rb
  spec/acceptance/agent_status_check_spec.rb
  spec/acceptance/pe_status_check_spec.rb
  spec/classes/pe_status_check_spec.rb
Labels: backwards-incompatible

#77 Resolves Documentation Errors
  README.md
Labels: maintenance

#76 Adds Details to Warning Messages
  data/common.yaml
  manifests/init.pp
  spec/acceptance/pe_status_check_spec.rb
Labels: enhancement

#78 SUP-2971 Requested review of README
  README.md
Labels: documentation, maintenance

#83 Module function
  lib/shared/pe_status_check.rb
Labels: enhancement

#85 (SUP-3004) correct formating issue in readme
  README.md
Labels: maintenance
