Repository puppetlabs/puppetlabs-pe_status_check, pull requests merged in 2023-05, with the labels that each got.

#190 Update version of node manager in fixtures
  .fixtures.yml
Labels: maintenance

#191 (SUP-4275) Update Hiera definition of S0038
  data/static.yaml
Labels: enhancement

#192 (SUP-4282) add error handling to S0044
  data/static.yaml
  lib/facter/pe_status_check.rb
Labels: bug
