Repository puppetlabs/puppetlabs-pe_status_check, pull requests merged in 2023-09, with the labels that each got.

#200 (SUP-4402) pe_status_check fails if hiera.yaml is empty
  lib/facter/pe_status_check.rb
Labels: bug

#202 (SUP-4316) remove problematic test fo s0019
  spec/acceptance/pe_status_check_spec.rb
Labels: maintenance

#199 Refactor hieradata into single hash
  data/static.yaml
  manifests/init.pp
  plans/agent_summary.pp
  plans/infra_summary.pp
Labels: backwards-incompatible
