Repository puppetlabs/puppetlabs-pe_status_check, pull requests merged in 2024-11, with the labels that each got.

#238 (#236) agent_state_summary: Count nodes without report as unhealthy
  README.md
  plans/agent_state_summary.pp
Labels: enhancement

#239 (maint) Pdk update
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .rubocop.yml
  .sync.yml
  .vscode/extensions.json
  Gemfile
  Rakefile
  metadata.json
  spec/default_facts.yml
  spec/spec_helper.rb
Labels: maintenance

#244 fix: prevent random failures in agent_status_check
  lib/facter/agent_status_check.rb
Labels: bug
